name: Check version on PR to master

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  check-version-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Get current api version from pom.xml
        id: api
        run: |
          cd api/pmt
          chmod +x ./mvnw
          version=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Get latest tag
        id: tag
        run: |
          latest_tag=$(git tag --sort=-creatordate | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT
          if [ -z "$latest_tag" ]; then
            echo "Aucun tag trouvé, la vérification de version est ignorée."
          fi

      - name: Compare version with latest tag
        run: |
          pkg_version=${{ steps.api.outputs.version }}
          latest_tag=${{ steps.tag.outputs.latest_tag }}
          if [ -z "$latest_tag" ]; then
            echo "Aucun tag de version trouvé, la vérification est ignorée."
            exit 0
          fi
          tag_version=${latest_tag#v}
          if [ "$pkg_version" = "$tag_version" ]; then
            echo "❌ La version de l'API ($pkg_version) n'a pas été modifiée depuis le dernier tag ($latest_tag). Veuillez incrémenter la version avant de merger."
            exit 1
          else
            echo "✅ La version de l'API ($pkg_version) est différente du dernier tag ($latest_tag)."
          fi
